plugins {
    id 'fabric-loom' version "${loom_version}"
    id 'maven-publish'
}

version = "${mod_version}-${minecraft_version}"
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    mavenCentral()

    maven {
        name = "Kosmx"
        url = "https://maven.kosmx.dev/"
    }

    maven {
        name = "Wisp Forest"
        url = "https://maven.wispforest.io/releases/"
    }

    maven {
        name = "Terraformers"
        url = "https://maven.terraformersmc.com/"
    }

    maven {
        name = "RedlanceMinecraft"
        url = "https://repo.redlance.org/public"
    }
}

fabricApi {
    configureDataGeneration {
        client = true
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    // Player Animation Library
    modImplementation "com.zigythebird.playeranim:PlayerAnimationLibFabric:$project.pal_version"

    // Mod Menu
    modImplementation "com.terraformersmc:modmenu:${project.modmenu_version}"

    // owo-lib
    annotationProcessor modImplementation("io.wispforest:owo-lib:${project.owo_version}")
    include "io.wispforest:owo-sentinel:${project.owo_version}"
}

processResources {
    var expandProps = [
            minecraft_version        : minecraft_version,
            mod_id                   : mod_id, mod_name: mod_name, mod_version: mod_version,
            mod_authors              : mod_authors, mod_description: mod_description,
            mod_page_url             : mod_page_url, mod_git_url: mod_git_url,
            mod_license              : mod_license
    ]

    filesMatching("fabric.mod.json") {
        expand expandProps
    }

    inputs.properties(expandProps)
}

java {
    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

jar {
    inputs.property "archivesName", project.base.archivesName

    from("LICENSE") {
        rename { "${it}_${inputs.properties.archivesName}" }
    }
}