# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.10
yarn_mappings=1.21.10+build.3
loader_version=0.18.1
loom_version=1.13-SNAPSHOT

# Mod Properties
mod_name=Vitality
mod_id=vitality
mod_version=1.1.1
mod_authors=uhmbyee / Mariany Pinkston
mod_description=Adds a diet system with movement buffs.
mod_page_url=https://www.curseforge.com/minecraft/mc-mods/vitality-diet-movement-buffs
mod_git_url=https://github.com/marianyp/vitality
mod_license=ARR

maven_group=dev.mariany.vitality
archives_base_name=vitality

# Dependencies
fabric_version=0.138.3+1.21.10
pal_version=1.1.2+mc.1.21.9
modmenu_version=16.0.0-rc.1
owo_version=0.12.24+1.21.9